settings:
  auto_translate: true
  desired_scenario: Reporting a lost or stolen card
  llm_select: gpt-3
  overwrite_sys_lang: true
  overwrite_token_limit: true
  practice_lang: en
  practice_lang_prof: beginner
  user_lang: pl
  user_profile: Basia
  user_token_limit: 5000
