settings:
  auto_translate: false
  overwrite_sys_lang: false
  overwrite_token_limit: false
  practice_lang: de
  practice_lang_prof: beginner
  user_lang: pl
  user_profile: Default
  user_token_limit: 3000
