settings:
  auto_translate: true
  desired_scenario: You are a hiring manager in LinguaFranka. The user is discussing
    salary and benefits. Engage in the discussion and provide necessary details.
  llm_select: gpt-3
  overwrite_sys_lang: true
  overwrite_token_limit: false
  practice_lang: English
  practice_lang_prof: proficient
  user_lang: Polish
  user_profile: Kamil
  user_token_limit: 3000
